// Code generated by ent, DO NOT EDIT.

package ssosession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/luckysxx/user-platform/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLTE(FieldID, id))
}

// SSOTokenHash applies equality check predicate on the "sso_token_hash" field. It's identical to SSOTokenHashEQ.
func SSOTokenHash(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldSSOTokenHash, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldDeviceID, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldUserAgent, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldIP, v))
}

// SSOVersion applies equality check predicate on the "sso_version" field. It's identical to SSOVersionEQ.
func SSOVersion(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldSSOVersion, v))
}

// UserVersion applies equality check predicate on the "user_version" field. It's identical to UserVersionEQ.
func UserVersion(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldUserVersion, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldExpiresAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldLastSeenAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldRevokedAt, v))
}

// SSOTokenHashEQ applies the EQ predicate on the "sso_token_hash" field.
func SSOTokenHashEQ(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldSSOTokenHash, v))
}

// SSOTokenHashNEQ applies the NEQ predicate on the "sso_token_hash" field.
func SSOTokenHashNEQ(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldSSOTokenHash, v))
}

// SSOTokenHashIn applies the In predicate on the "sso_token_hash" field.
func SSOTokenHashIn(vs ...string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldSSOTokenHash, vs...))
}

// SSOTokenHashNotIn applies the NotIn predicate on the "sso_token_hash" field.
func SSOTokenHashNotIn(vs ...string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldSSOTokenHash, vs...))
}

// SSOTokenHashGT applies the GT predicate on the "sso_token_hash" field.
func SSOTokenHashGT(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGT(FieldSSOTokenHash, v))
}

// SSOTokenHashGTE applies the GTE predicate on the "sso_token_hash" field.
func SSOTokenHashGTE(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGTE(FieldSSOTokenHash, v))
}

// SSOTokenHashLT applies the LT predicate on the "sso_token_hash" field.
func SSOTokenHashLT(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLT(FieldSSOTokenHash, v))
}

// SSOTokenHashLTE applies the LTE predicate on the "sso_token_hash" field.
func SSOTokenHashLTE(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLTE(FieldSSOTokenHash, v))
}

// SSOTokenHashContains applies the Contains predicate on the "sso_token_hash" field.
func SSOTokenHashContains(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldContains(FieldSSOTokenHash, v))
}

// SSOTokenHashHasPrefix applies the HasPrefix predicate on the "sso_token_hash" field.
func SSOTokenHashHasPrefix(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldHasPrefix(FieldSSOTokenHash, v))
}

// SSOTokenHashHasSuffix applies the HasSuffix predicate on the "sso_token_hash" field.
func SSOTokenHashHasSuffix(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldHasSuffix(FieldSSOTokenHash, v))
}

// SSOTokenHashEqualFold applies the EqualFold predicate on the "sso_token_hash" field.
func SSOTokenHashEqualFold(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEqualFold(FieldSSOTokenHash, v))
}

// SSOTokenHashContainsFold applies the ContainsFold predicate on the "sso_token_hash" field.
func SSOTokenHashContainsFold(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldContainsFold(FieldSSOTokenHash, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDIsNil applies the IsNil predicate on the "device_id" field.
func DeviceIDIsNil() predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIsNull(FieldDeviceID))
}

// DeviceIDNotNil applies the NotNil predicate on the "device_id" field.
func DeviceIDNotNil() predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotNull(FieldDeviceID))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldContainsFold(FieldDeviceID, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldContainsFold(FieldUserAgent, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldHasSuffix(FieldIP, v))
}

// IPIsNil applies the IsNil predicate on the "ip" field.
func IPIsNil() predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIsNull(FieldIP))
}

// IPNotNil applies the NotNil predicate on the "ip" field.
func IPNotNil() predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotNull(FieldIP))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldContainsFold(FieldIP, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldStatus, vs...))
}

// SSOVersionEQ applies the EQ predicate on the "sso_version" field.
func SSOVersionEQ(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldSSOVersion, v))
}

// SSOVersionNEQ applies the NEQ predicate on the "sso_version" field.
func SSOVersionNEQ(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldSSOVersion, v))
}

// SSOVersionIn applies the In predicate on the "sso_version" field.
func SSOVersionIn(vs ...int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldSSOVersion, vs...))
}

// SSOVersionNotIn applies the NotIn predicate on the "sso_version" field.
func SSOVersionNotIn(vs ...int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldSSOVersion, vs...))
}

// SSOVersionGT applies the GT predicate on the "sso_version" field.
func SSOVersionGT(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGT(FieldSSOVersion, v))
}

// SSOVersionGTE applies the GTE predicate on the "sso_version" field.
func SSOVersionGTE(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGTE(FieldSSOVersion, v))
}

// SSOVersionLT applies the LT predicate on the "sso_version" field.
func SSOVersionLT(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLT(FieldSSOVersion, v))
}

// SSOVersionLTE applies the LTE predicate on the "sso_version" field.
func SSOVersionLTE(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLTE(FieldSSOVersion, v))
}

// UserVersionEQ applies the EQ predicate on the "user_version" field.
func UserVersionEQ(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldUserVersion, v))
}

// UserVersionNEQ applies the NEQ predicate on the "user_version" field.
func UserVersionNEQ(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldUserVersion, v))
}

// UserVersionIn applies the In predicate on the "user_version" field.
func UserVersionIn(vs ...int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldUserVersion, vs...))
}

// UserVersionNotIn applies the NotIn predicate on the "user_version" field.
func UserVersionNotIn(vs ...int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldUserVersion, vs...))
}

// UserVersionGT applies the GT predicate on the "user_version" field.
func UserVersionGT(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGT(FieldUserVersion, v))
}

// UserVersionGTE applies the GTE predicate on the "user_version" field.
func UserVersionGTE(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGTE(FieldUserVersion, v))
}

// UserVersionLT applies the LT predicate on the "user_version" field.
func UserVersionLT(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLT(FieldUserVersion, v))
}

// UserVersionLTE applies the LTE predicate on the "user_version" field.
func UserVersionLTE(v int64) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLTE(FieldUserVersion, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLTE(FieldExpiresAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLTE(FieldLastSeenAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.SsoSession {
	return predicate.SsoSession(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.SsoSession {
	return predicate.SsoSession(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.SsoSession {
	return predicate.SsoSession(sql.FieldNotNull(FieldRevokedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SsoSession {
	return predicate.SsoSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SsoSession {
	return predicate.SsoSession(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIdentity applies the HasEdge predicate on the "identity" edge.
func HasIdentity() predicate.SsoSession {
	return predicate.SsoSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IdentityTable, IdentityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIdentityWith applies the HasEdge predicate on the "identity" edge with a given conditions (other predicates).
func HasIdentityWith(preds ...predicate.UserIdentity) predicate.SsoSession {
	return predicate.SsoSession(func(s *sql.Selector) {
		step := newIdentityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSessions applies the HasEdge predicate on the "sessions" edge.
func HasSessions() predicate.SsoSession {
	return predicate.SsoSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionsWith applies the HasEdge predicate on the "sessions" edge with a given conditions (other predicates).
func HasSessionsWith(preds ...predicate.Session) predicate.SsoSession {
	return predicate.SsoSession(func(s *sql.Selector) {
		step := newSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SsoSession) predicate.SsoSession {
	return predicate.SsoSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SsoSession) predicate.SsoSession {
	return predicate.SsoSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SsoSession) predicate.SsoSession {
	return predicate.SsoSession(sql.NotPredicates(p))
}
