// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppsColumns holds the columns for the "apps" table.
	AppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "app_code", Type: field.TypeString, Unique: true},
		{Name: "app_name", Type: field.TypeString},
	}
	// AppsTable holds the schema information for the "apps" table.
	AppsTable = &schema.Table{
		Name:       "apps",
		Columns:    AppsColumns,
		PrimaryKey: []*schema.Column{AppsColumns[0]},
	}
	// EventOutboxesColumns holds the columns for the "event_outboxes" table.
	EventOutboxesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "aggregatetype", Type: field.TypeString, Nullable: true},
		{Name: "aggregateid", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeString, Nullable: true},
		{Name: "payload", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "headers", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "created_at", Type: field.TypeTime},
	}
	// EventOutboxesTable holds the schema information for the "event_outboxes" table.
	EventOutboxesTable = &schema.Table{
		Name:       "event_outboxes",
		Columns:    EventOutboxesColumns,
		PrimaryKey: []*schema.Column{EventOutboxesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "eventoutbox_aggregatetype_aggregateid",
				Unique:  false,
				Columns: []*schema.Column{EventOutboxesColumns[1], EventOutboxesColumns[2]},
			},
			{
				Name:    "eventoutbox_type_created_at",
				Unique:  false,
				Columns: []*schema.Column{EventOutboxesColumns[3], EventOutboxesColumns[6]},
			},
		},
	}
	// ProfilesColumns holds the columns for the "profiles" table.
	ProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "nickname", Type: field.TypeString, Size: 32, Default: ""},
		{Name: "avatar_url", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "bio", Type: field.TypeString, Size: 256, Default: ""},
		{Name: "birthday", Type: field.TypeString, Size: 10, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_profile", Type: field.TypeInt64, Unique: true},
	}
	// ProfilesTable holds the schema information for the "profiles" table.
	ProfilesTable = &schema.Table{
		Name:       "profiles",
		Columns:    ProfilesColumns,
		PrimaryKey: []*schema.Column{ProfilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "profiles_users_profile",
				Columns:    []*schema.Column{ProfilesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "session_token_hash", Type: field.TypeString, Unique: true},
		{Name: "device_id", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "ip", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "revoked", "expired"}, Default: "active"},
		{Name: "version", Type: field.TypeInt64, Default: 1},
		{Name: "user_version", Type: field.TypeInt64, Default: 1},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "app_sessions", Type: field.TypeInt},
		{Name: "sso_session_sessions", Type: field.TypeUUID, Nullable: true},
		{Name: "user_sessions", Type: field.TypeInt64},
		{Name: "user_identity_sessions", Type: field.TypeInt, Nullable: true},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_apps_sessions",
				Columns:    []*schema.Column{SessionsColumns[11]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sessions_sso_sessions_sessions",
				Columns:    []*schema.Column{SessionsColumns[12]},
				RefColumns: []*schema.Column{SSOSessionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[13]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sessions_user_identities_sessions",
				Columns:    []*schema.Column{SessionsColumns[14]},
				RefColumns: []*schema.Column{UserIdentitiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "session_user_sessions",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[13]},
			},
			{
				Name:    "session_user_sessions_app_sessions",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[13], SessionsColumns[11]},
			},
		},
	}
	// SSOSessionsColumns holds the columns for the "sso_sessions" table.
	SSOSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "sso_token_hash", Type: field.TypeString, Unique: true},
		{Name: "device_id", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "ip", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "revoked", "expired"}, Default: "active"},
		{Name: "sso_version", Type: field.TypeInt64, Default: 1},
		{Name: "user_version", Type: field.TypeInt64, Default: 1},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_sso_sessions", Type: field.TypeInt64},
		{Name: "user_identity_sso_sessions", Type: field.TypeInt, Nullable: true},
	}
	// SSOSessionsTable holds the schema information for the "sso_sessions" table.
	SSOSessionsTable = &schema.Table{
		Name:       "sso_sessions",
		Columns:    SSOSessionsColumns,
		PrimaryKey: []*schema.Column{SSOSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sso_sessions_users_sso_sessions",
				Columns:    []*schema.Column{SSOSessionsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sso_sessions_user_identities_sso_sessions",
				Columns:    []*schema.Column{SSOSessionsColumns[12]},
				RefColumns: []*schema.Column{UserIdentitiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "ssosession_user_sso_sessions",
				Unique:  false,
				Columns: []*schema.Column{SSOSessionsColumns[11]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_version", Type: field.TypeInt64, Default: 1},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "banned", "deleted"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserAppAuthorizationsColumns holds the columns for the "user_app_authorizations" table.
	UserAppAuthorizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "revoked", "banned"}, Default: "active"},
		{Name: "scopes", Type: field.TypeJSON},
		{Name: "ext_profile", Type: field.TypeJSON},
		{Name: "first_authorized_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_active_at", Type: field.TypeTime},
		{Name: "app_authorizations", Type: field.TypeInt},
		{Name: "user_authorizations", Type: field.TypeInt64},
		{Name: "user_identity_authorizations", Type: field.TypeInt, Nullable: true},
	}
	// UserAppAuthorizationsTable holds the schema information for the "user_app_authorizations" table.
	UserAppAuthorizationsTable = &schema.Table{
		Name:       "user_app_authorizations",
		Columns:    UserAppAuthorizationsColumns,
		PrimaryKey: []*schema.Column{UserAppAuthorizationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_app_authorizations_apps_authorizations",
				Columns:    []*schema.Column{UserAppAuthorizationsColumns[7]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_app_authorizations_users_authorizations",
				Columns:    []*schema.Column{UserAppAuthorizationsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_app_authorizations_user_identities_authorizations",
				Columns:    []*schema.Column{UserAppAuthorizationsColumns[9]},
				RefColumns: []*schema.Column{UserIdentitiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userappauthorization_user_authorizations_app_authorizations",
				Unique:  true,
				Columns: []*schema.Column{UserAppAuthorizationsColumns[8], UserAppAuthorizationsColumns[7]},
			},
		},
	}
	// UserIdentitiesColumns holds the columns for the "user_identities" table.
	UserIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider", Type: field.TypeEnum, Enums: []string{"phone", "email", "username", "github", "qq", "wechat"}},
		{Name: "provider_uid", Type: field.TypeString, Size: 255},
		{Name: "provider_union_id", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "login_name", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "credential_hash", Type: field.TypeString, Nullable: true},
		{Name: "verified_at", Type: field.TypeTime, Nullable: true},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "meta", Type: field.TypeJSON},
		{Name: "user_identities", Type: field.TypeInt64},
	}
	// UserIdentitiesTable holds the schema information for the "user_identities" table.
	UserIdentitiesTable = &schema.Table{
		Name:       "user_identities",
		Columns:    UserIdentitiesColumns,
		PrimaryKey: []*schema.Column{UserIdentitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_identities_users_identities",
				Columns:    []*schema.Column{UserIdentitiesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "useridentity_provider_provider_uid",
				Unique:  true,
				Columns: []*schema.Column{UserIdentitiesColumns[1], UserIdentitiesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppsTable,
		EventOutboxesTable,
		ProfilesTable,
		SessionsTable,
		SSOSessionsTable,
		UsersTable,
		UserAppAuthorizationsTable,
		UserIdentitiesTable,
	}
)

func init() {
	ProfilesTable.ForeignKeys[0].RefTable = UsersTable
	SessionsTable.ForeignKeys[0].RefTable = AppsTable
	SessionsTable.ForeignKeys[1].RefTable = SSOSessionsTable
	SessionsTable.ForeignKeys[2].RefTable = UsersTable
	SessionsTable.ForeignKeys[3].RefTable = UserIdentitiesTable
	SSOSessionsTable.ForeignKeys[0].RefTable = UsersTable
	SSOSessionsTable.ForeignKeys[1].RefTable = UserIdentitiesTable
	UserAppAuthorizationsTable.ForeignKeys[0].RefTable = AppsTable
	UserAppAuthorizationsTable.ForeignKeys[1].RefTable = UsersTable
	UserAppAuthorizationsTable.ForeignKeys[2].RefTable = UserIdentitiesTable
	UserIdentitiesTable.ForeignKeys[0].RefTable = UsersTable
}
