// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppsColumns holds the columns for the "apps" table.
	AppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "app_code", Type: field.TypeString, Unique: true},
		{Name: "app_name", Type: field.TypeString},
	}
	// AppsTable holds the schema information for the "apps" table.
	AppsTable = &schema.Table{
		Name:       "apps",
		Columns:    AppsColumns,
		PrimaryKey: []*schema.Column{AppsColumns[0]},
	}
	// EventOutboxesColumns holds the columns for the "event_outboxes" table.
	EventOutboxesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "topic", Type: field.TypeString},
		{Name: "payload", Type: field.TypeBytes},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "success", "failed"}, Default: "pending"},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// EventOutboxesTable holds the schema information for the "event_outboxes" table.
	EventOutboxesTable = &schema.Table{
		Name:       "event_outboxes",
		Columns:    EventOutboxesColumns,
		PrimaryKey: []*schema.Column{EventOutboxesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "eventoutbox_status_retry_count",
				Unique:  false,
				Columns: []*schema.Column{EventOutboxesColumns[3], EventOutboxesColumns[4]},
			},
			{
				Name:    "eventoutbox_status_updated_at",
				Unique:  false,
				Columns: []*schema.Column{EventOutboxesColumns[3], EventOutboxesColumns[6]},
			},
		},
	}
	// ProfilesColumns holds the columns for the "profiles" table.
	ProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "nickname", Type: field.TypeString, Size: 32, Default: ""},
		{Name: "avatar_url", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "bio", Type: field.TypeString, Size: 256, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_profile", Type: field.TypeInt64, Unique: true},
	}
	// ProfilesTable holds the schema information for the "profiles" table.
	ProfilesTable = &schema.Table{
		Name:       "profiles",
		Columns:    ProfilesColumns,
		PrimaryKey: []*schema.Column{ProfilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "profiles_users_profile",
				Columns:    []*schema.Column{ProfilesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "password", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "banned", "deleted"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserAppProfilesColumns holds the columns for the "user_app_profiles" table.
	UserAppProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "first_authorized_at", Type: field.TypeTime},
		{Name: "last_active_at", Type: field.TypeTime},
		{Name: "app_profiles", Type: field.TypeInt},
		{Name: "user_profiles", Type: field.TypeInt64},
	}
	// UserAppProfilesTable holds the schema information for the "user_app_profiles" table.
	UserAppProfilesTable = &schema.Table{
		Name:       "user_app_profiles",
		Columns:    UserAppProfilesColumns,
		PrimaryKey: []*schema.Column{UserAppProfilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_app_profiles_apps_profiles",
				Columns:    []*schema.Column{UserAppProfilesColumns[3]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_app_profiles_users_profiles",
				Columns:    []*schema.Column{UserAppProfilesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppsTable,
		EventOutboxesTable,
		ProfilesTable,
		UsersTable,
		UserAppProfilesTable,
	}
)

func init() {
	ProfilesTable.ForeignKeys[0].RefTable = UsersTable
	UserAppProfilesTable.ForeignKeys[0].RefTable = AppsTable
	UserAppProfilesTable.ForeignKeys[1].RefTable = UsersTable
}
