// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/user-platform/internal/ent/eventoutbox"
	"github.com/luckysxx/user-platform/internal/ent/predicate"
)

// EventOutboxUpdate is the builder for updating EventOutbox entities.
type EventOutboxUpdate struct {
	config
	hooks    []Hook
	mutation *EventOutboxMutation
}

// Where appends a list predicates to the EventOutboxUpdate builder.
func (_u *EventOutboxUpdate) Where(ps ...predicate.EventOutbox) *EventOutboxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTopic sets the "topic" field.
func (_u *EventOutboxUpdate) SetTopic(v string) *EventOutboxUpdate {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *EventOutboxUpdate) SetNillableTopic(v *string) *EventOutboxUpdate {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *EventOutboxUpdate) SetPayload(v []byte) *EventOutboxUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EventOutboxUpdate) SetStatus(v eventoutbox.Status) *EventOutboxUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventOutboxUpdate) SetNillableStatus(v *eventoutbox.Status) *EventOutboxUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *EventOutboxUpdate) SetRetryCount(v int) *EventOutboxUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *EventOutboxUpdate) SetNillableRetryCount(v *int) *EventOutboxUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *EventOutboxUpdate) AddRetryCount(v int) *EventOutboxUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EventOutboxUpdate) SetCreatedAt(v time.Time) *EventOutboxUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EventOutboxUpdate) SetNillableCreatedAt(v *time.Time) *EventOutboxUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventOutboxUpdate) SetUpdatedAt(v time.Time) *EventOutboxUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EventOutboxMutation object of the builder.
func (_u *EventOutboxUpdate) Mutation() *EventOutboxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventOutboxUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventOutboxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventOutboxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventOutboxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventOutboxUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := eventoutbox.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventOutboxUpdate) check() error {
	if v, ok := _u.mutation.Topic(); ok {
		if err := eventoutbox.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "EventOutbox.topic": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Payload(); ok {
		if err := eventoutbox.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "EventOutbox.payload": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := eventoutbox.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EventOutbox.status": %w`, err)}
		}
	}
	return nil
}

func (_u *EventOutboxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventoutbox.Table, eventoutbox.Columns, sqlgraph.NewFieldSpec(eventoutbox.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(eventoutbox.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(eventoutbox.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(eventoutbox.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(eventoutbox.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(eventoutbox.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(eventoutbox.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(eventoutbox.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventOutboxUpdateOne is the builder for updating a single EventOutbox entity.
type EventOutboxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventOutboxMutation
}

// SetTopic sets the "topic" field.
func (_u *EventOutboxUpdateOne) SetTopic(v string) *EventOutboxUpdateOne {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *EventOutboxUpdateOne) SetNillableTopic(v *string) *EventOutboxUpdateOne {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *EventOutboxUpdateOne) SetPayload(v []byte) *EventOutboxUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EventOutboxUpdateOne) SetStatus(v eventoutbox.Status) *EventOutboxUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventOutboxUpdateOne) SetNillableStatus(v *eventoutbox.Status) *EventOutboxUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *EventOutboxUpdateOne) SetRetryCount(v int) *EventOutboxUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *EventOutboxUpdateOne) SetNillableRetryCount(v *int) *EventOutboxUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *EventOutboxUpdateOne) AddRetryCount(v int) *EventOutboxUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EventOutboxUpdateOne) SetCreatedAt(v time.Time) *EventOutboxUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EventOutboxUpdateOne) SetNillableCreatedAt(v *time.Time) *EventOutboxUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventOutboxUpdateOne) SetUpdatedAt(v time.Time) *EventOutboxUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EventOutboxMutation object of the builder.
func (_u *EventOutboxUpdateOne) Mutation() *EventOutboxMutation {
	return _u.mutation
}

// Where appends a list predicates to the EventOutboxUpdate builder.
func (_u *EventOutboxUpdateOne) Where(ps ...predicate.EventOutbox) *EventOutboxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventOutboxUpdateOne) Select(field string, fields ...string) *EventOutboxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EventOutbox entity.
func (_u *EventOutboxUpdateOne) Save(ctx context.Context) (*EventOutbox, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventOutboxUpdateOne) SaveX(ctx context.Context) *EventOutbox {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventOutboxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventOutboxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventOutboxUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := eventoutbox.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventOutboxUpdateOne) check() error {
	if v, ok := _u.mutation.Topic(); ok {
		if err := eventoutbox.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "EventOutbox.topic": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Payload(); ok {
		if err := eventoutbox.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "EventOutbox.payload": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := eventoutbox.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EventOutbox.status": %w`, err)}
		}
	}
	return nil
}

func (_u *EventOutboxUpdateOne) sqlSave(ctx context.Context) (_node *EventOutbox, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventoutbox.Table, eventoutbox.Columns, sqlgraph.NewFieldSpec(eventoutbox.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EventOutbox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventoutbox.FieldID)
		for _, f := range fields {
			if !eventoutbox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != eventoutbox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(eventoutbox.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(eventoutbox.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(eventoutbox.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(eventoutbox.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(eventoutbox.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(eventoutbox.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(eventoutbox.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &EventOutbox{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
