// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/user-platform/internal/ent/eventoutbox"
)

// EventOutboxCreate is the builder for creating a EventOutbox entity.
type EventOutboxCreate struct {
	config
	mutation *EventOutboxMutation
	hooks    []Hook
}

// SetTopic sets the "topic" field.
func (_c *EventOutboxCreate) SetTopic(v string) *EventOutboxCreate {
	_c.mutation.SetTopic(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *EventOutboxCreate) SetPayload(v []byte) *EventOutboxCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *EventOutboxCreate) SetStatus(v eventoutbox.Status) *EventOutboxCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EventOutboxCreate) SetNillableStatus(v *eventoutbox.Status) *EventOutboxCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *EventOutboxCreate) SetRetryCount(v int) *EventOutboxCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *EventOutboxCreate) SetNillableRetryCount(v *int) *EventOutboxCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventOutboxCreate) SetCreatedAt(v time.Time) *EventOutboxCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventOutboxCreate) SetNillableCreatedAt(v *time.Time) *EventOutboxCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventOutboxCreate) SetUpdatedAt(v time.Time) *EventOutboxCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventOutboxCreate) SetNillableUpdatedAt(v *time.Time) *EventOutboxCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the EventOutboxMutation object of the builder.
func (_c *EventOutboxCreate) Mutation() *EventOutboxMutation {
	return _c.mutation
}

// Save creates the EventOutbox in the database.
func (_c *EventOutboxCreate) Save(ctx context.Context) (*EventOutbox, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventOutboxCreate) SaveX(ctx context.Context) *EventOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventOutboxCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventOutboxCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventOutboxCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := eventoutbox.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := eventoutbox.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := eventoutbox.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := eventoutbox.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventOutboxCreate) check() error {
	if _, ok := _c.mutation.Topic(); !ok {
		return &ValidationError{Name: "topic", err: errors.New(`ent: missing required field "EventOutbox.topic"`)}
	}
	if v, ok := _c.mutation.Topic(); ok {
		if err := eventoutbox.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "EventOutbox.topic": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "EventOutbox.payload"`)}
	}
	if v, ok := _c.mutation.Payload(); ok {
		if err := eventoutbox.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "EventOutbox.payload": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EventOutbox.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := eventoutbox.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EventOutbox.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "EventOutbox.retry_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EventOutbox.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EventOutbox.updated_at"`)}
	}
	return nil
}

func (_c *EventOutboxCreate) sqlSave(ctx context.Context) (*EventOutbox, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventOutboxCreate) createSpec() (*EventOutbox, *sqlgraph.CreateSpec) {
	var (
		_node = &EventOutbox{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(eventoutbox.Table, sqlgraph.NewFieldSpec(eventoutbox.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Topic(); ok {
		_spec.SetField(eventoutbox.FieldTopic, field.TypeString, value)
		_node.Topic = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(eventoutbox.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(eventoutbox.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(eventoutbox.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(eventoutbox.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(eventoutbox.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// EventOutboxCreateBulk is the builder for creating many EventOutbox entities in bulk.
type EventOutboxCreateBulk struct {
	config
	err      error
	builders []*EventOutboxCreate
}

// Save creates the EventOutbox entities in the database.
func (_c *EventOutboxCreateBulk) Save(ctx context.Context) ([]*EventOutbox, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EventOutbox, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventOutboxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventOutboxCreateBulk) SaveX(ctx context.Context) []*EventOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventOutboxCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventOutboxCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
