// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/luckysxx/user-platform/internal/ent/eventoutbox"
)

// EventOutbox is the model entity for the EventOutbox schema.
type EventOutbox struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 聚合类型，如 user / paste；主要用于表达这条事件属于哪个聚合
	Aggregatetype *string `json:"aggregatetype,omitempty"`
	// 聚合根 ID，如 userID / pasteID；当前会被 Debezium Outbox Router 映射为 Kafka message key
	Aggregateid *string `json:"aggregateid,omitempty"`
	// 领域事件类型，如 user.registered；当前会被 Debezium Outbox Router 用作 Kafka topic 路由字段
	Type *string `json:"type,omitempty"`
	// 事件消息体；当前会被 Debezium Outbox Router 映射为 Kafka message value
	Payload json.RawMessage `json:"payload,omitempty"`
	// 可选事件头；当前会被 Debezium Outbox Router 映射为 Kafka headers，预留给 trace/source 等元数据
	Headers json.RawMessage `json:"headers,omitempty"`
	// Outbox 记录创建时间；主要用于审计、排查和按时间维度查询
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EventOutbox) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case eventoutbox.FieldPayload, eventoutbox.FieldHeaders:
			values[i] = new([]byte)
		case eventoutbox.FieldID:
			values[i] = new(sql.NullInt64)
		case eventoutbox.FieldAggregatetype, eventoutbox.FieldAggregateid, eventoutbox.FieldType:
			values[i] = new(sql.NullString)
		case eventoutbox.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EventOutbox fields.
func (_m *EventOutbox) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case eventoutbox.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case eventoutbox.FieldAggregatetype:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aggregatetype", values[i])
			} else if value.Valid {
				_m.Aggregatetype = new(string)
				*_m.Aggregatetype = value.String
			}
		case eventoutbox.FieldAggregateid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aggregateid", values[i])
			} else if value.Valid {
				_m.Aggregateid = new(string)
				*_m.Aggregateid = value.String
			}
		case eventoutbox.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = new(string)
				*_m.Type = value.String
			}
		case eventoutbox.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case eventoutbox.FieldHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Headers); err != nil {
					return fmt.Errorf("unmarshal field headers: %w", err)
				}
			}
		case eventoutbox.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EventOutbox.
// This includes values selected through modifiers, order, etc.
func (_m *EventOutbox) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this EventOutbox.
// Note that you need to call EventOutbox.Unwrap() before calling this method if this EventOutbox
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EventOutbox) Update() *EventOutboxUpdateOne {
	return NewEventOutboxClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EventOutbox entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EventOutbox) Unwrap() *EventOutbox {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EventOutbox is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EventOutbox) String() string {
	var builder strings.Builder
	builder.WriteString("EventOutbox(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.Aggregatetype; v != nil {
		builder.WriteString("aggregatetype=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Aggregateid; v != nil {
		builder.WriteString("aggregateid=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Type; v != nil {
		builder.WriteString("type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.Headers))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EventOutboxes is a parsable slice of EventOutbox.
type EventOutboxes []*EventOutbox
