// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/luckysxx/user-platform/internal/ent/app"
	"github.com/luckysxx/user-platform/internal/ent/eventoutbox"
	"github.com/luckysxx/user-platform/internal/ent/profile"
	"github.com/luckysxx/user-platform/internal/ent/schema"
	"github.com/luckysxx/user-platform/internal/ent/user"
	"github.com/luckysxx/user-platform/internal/ent/userappprofile"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescAppCode is the schema descriptor for app_code field.
	appDescAppCode := appFields[0].Descriptor()
	// app.AppCodeValidator is a validator for the "app_code" field. It is called by the builders before save.
	app.AppCodeValidator = appDescAppCode.Validators[0].(func(string) error)
	// appDescAppName is the schema descriptor for app_name field.
	appDescAppName := appFields[1].Descriptor()
	// app.AppNameValidator is a validator for the "app_name" field. It is called by the builders before save.
	app.AppNameValidator = appDescAppName.Validators[0].(func(string) error)
	eventoutboxFields := schema.EventOutbox{}.Fields()
	_ = eventoutboxFields
	// eventoutboxDescCreatedAt is the schema descriptor for created_at field.
	eventoutboxDescCreatedAt := eventoutboxFields[5].Descriptor()
	// eventoutbox.DefaultCreatedAt holds the default value on creation for the created_at field.
	eventoutbox.DefaultCreatedAt = eventoutboxDescCreatedAt.Default.(func() time.Time)
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescNickname is the schema descriptor for nickname field.
	profileDescNickname := profileFields[1].Descriptor()
	// profile.DefaultNickname holds the default value on creation for the nickname field.
	profile.DefaultNickname = profileDescNickname.Default.(string)
	// profile.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	profile.NicknameValidator = profileDescNickname.Validators[0].(func(string) error)
	// profileDescAvatarURL is the schema descriptor for avatar_url field.
	profileDescAvatarURL := profileFields[2].Descriptor()
	// profile.DefaultAvatarURL holds the default value on creation for the avatar_url field.
	profile.DefaultAvatarURL = profileDescAvatarURL.Default.(string)
	// profile.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	profile.AvatarURLValidator = profileDescAvatarURL.Validators[0].(func(string) error)
	// profileDescBio is the schema descriptor for bio field.
	profileDescBio := profileFields[3].Descriptor()
	// profile.DefaultBio holds the default value on creation for the bio field.
	profile.DefaultBio = profileDescBio.Default.(string)
	// profile.BioValidator is a validator for the "bio" field. It is called by the builders before save.
	profile.BioValidator = profileDescBio.Validators[0].(func(string) error)
	// profileDescBirthday is the schema descriptor for birthday field.
	profileDescBirthday := profileFields[4].Descriptor()
	// profile.DefaultBirthday holds the default value on creation for the birthday field.
	profile.DefaultBirthday = profileDescBirthday.Default.(string)
	// profile.BirthdayValidator is a validator for the "birthday" field. It is called by the builders before save.
	profile.BirthdayValidator = profileDescBirthday.Validators[0].(func(string) error)
	// profileDescUpdatedAt is the schema descriptor for updated_at field.
	profileDescUpdatedAt := profileFields[5].Descriptor()
	// profile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profile.DefaultUpdatedAt = profileDescUpdatedAt.Default.(func() time.Time)
	// profile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	profile.UpdateDefaultUpdatedAt = profileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// profileDescID is the schema descriptor for id field.
	profileDescID := profileFields[0].Descriptor()
	// profile.IDValidator is a validator for the "id" field. It is called by the builders before save.
	profile.IDValidator = profileDescID.Validators[0].(func(int64) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[2].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int64) error)
	userappprofileFields := schema.UserAppProfile{}.Fields()
	_ = userappprofileFields
	// userappprofileDescFirstAuthorizedAt is the schema descriptor for first_authorized_at field.
	userappprofileDescFirstAuthorizedAt := userappprofileFields[0].Descriptor()
	// userappprofile.DefaultFirstAuthorizedAt holds the default value on creation for the first_authorized_at field.
	userappprofile.DefaultFirstAuthorizedAt = userappprofileDescFirstAuthorizedAt.Default.(func() time.Time)
	// userappprofileDescLastActiveAt is the schema descriptor for last_active_at field.
	userappprofileDescLastActiveAt := userappprofileFields[1].Descriptor()
	// userappprofile.DefaultLastActiveAt holds the default value on creation for the last_active_at field.
	userappprofile.DefaultLastActiveAt = userappprofileDescLastActiveAt.Default.(func() time.Time)
	// userappprofile.UpdateDefaultLastActiveAt holds the default value on update for the last_active_at field.
	userappprofile.UpdateDefaultLastActiveAt = userappprofileDescLastActiveAt.UpdateDefault.(func() time.Time)
}
