// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/luckysxx/user-platform/internal/ent/app"
	"github.com/luckysxx/user-platform/internal/ent/eventoutbox"
	"github.com/luckysxx/user-platform/internal/ent/profile"
	"github.com/luckysxx/user-platform/internal/ent/schema"
	"github.com/luckysxx/user-platform/internal/ent/session"
	"github.com/luckysxx/user-platform/internal/ent/ssosession"
	"github.com/luckysxx/user-platform/internal/ent/user"
	"github.com/luckysxx/user-platform/internal/ent/userappauthorization"
	"github.com/luckysxx/user-platform/internal/ent/useridentity"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescAppCode is the schema descriptor for app_code field.
	appDescAppCode := appFields[0].Descriptor()
	// app.AppCodeValidator is a validator for the "app_code" field. It is called by the builders before save.
	app.AppCodeValidator = appDescAppCode.Validators[0].(func(string) error)
	// appDescAppName is the schema descriptor for app_name field.
	appDescAppName := appFields[1].Descriptor()
	// app.AppNameValidator is a validator for the "app_name" field. It is called by the builders before save.
	app.AppNameValidator = appDescAppName.Validators[0].(func(string) error)
	eventoutboxFields := schema.EventOutbox{}.Fields()
	_ = eventoutboxFields
	// eventoutboxDescCreatedAt is the schema descriptor for created_at field.
	eventoutboxDescCreatedAt := eventoutboxFields[5].Descriptor()
	// eventoutbox.DefaultCreatedAt holds the default value on creation for the created_at field.
	eventoutbox.DefaultCreatedAt = eventoutboxDescCreatedAt.Default.(func() time.Time)
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescNickname is the schema descriptor for nickname field.
	profileDescNickname := profileFields[1].Descriptor()
	// profile.DefaultNickname holds the default value on creation for the nickname field.
	profile.DefaultNickname = profileDescNickname.Default.(string)
	// profile.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	profile.NicknameValidator = profileDescNickname.Validators[0].(func(string) error)
	// profileDescAvatarURL is the schema descriptor for avatar_url field.
	profileDescAvatarURL := profileFields[2].Descriptor()
	// profile.DefaultAvatarURL holds the default value on creation for the avatar_url field.
	profile.DefaultAvatarURL = profileDescAvatarURL.Default.(string)
	// profile.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	profile.AvatarURLValidator = profileDescAvatarURL.Validators[0].(func(string) error)
	// profileDescBio is the schema descriptor for bio field.
	profileDescBio := profileFields[3].Descriptor()
	// profile.DefaultBio holds the default value on creation for the bio field.
	profile.DefaultBio = profileDescBio.Default.(string)
	// profile.BioValidator is a validator for the "bio" field. It is called by the builders before save.
	profile.BioValidator = profileDescBio.Validators[0].(func(string) error)
	// profileDescBirthday is the schema descriptor for birthday field.
	profileDescBirthday := profileFields[4].Descriptor()
	// profile.DefaultBirthday holds the default value on creation for the birthday field.
	profile.DefaultBirthday = profileDescBirthday.Default.(string)
	// profile.BirthdayValidator is a validator for the "birthday" field. It is called by the builders before save.
	profile.BirthdayValidator = profileDescBirthday.Validators[0].(func(string) error)
	// profileDescUpdatedAt is the schema descriptor for updated_at field.
	profileDescUpdatedAt := profileFields[5].Descriptor()
	// profile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profile.DefaultUpdatedAt = profileDescUpdatedAt.Default.(func() time.Time)
	// profile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	profile.UpdateDefaultUpdatedAt = profileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// profileDescID is the schema descriptor for id field.
	profileDescID := profileFields[0].Descriptor()
	// profile.IDValidator is a validator for the "id" field. It is called by the builders before save.
	profile.IDValidator = profileDescID.Validators[0].(func(int64) error)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescSessionTokenHash is the schema descriptor for session_token_hash field.
	sessionDescSessionTokenHash := sessionFields[1].Descriptor()
	// session.SessionTokenHashValidator is a validator for the "session_token_hash" field. It is called by the builders before save.
	session.SessionTokenHashValidator = sessionDescSessionTokenHash.Validators[0].(func(string) error)
	// sessionDescDeviceID is the schema descriptor for device_id field.
	sessionDescDeviceID := sessionFields[2].Descriptor()
	// session.DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	session.DeviceIDValidator = sessionDescDeviceID.Validators[0].(func(string) error)
	// sessionDescUserAgent is the schema descriptor for user_agent field.
	sessionDescUserAgent := sessionFields[3].Descriptor()
	// session.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	session.UserAgentValidator = sessionDescUserAgent.Validators[0].(func(string) error)
	// sessionDescVersion is the schema descriptor for version field.
	sessionDescVersion := sessionFields[6].Descriptor()
	// session.DefaultVersion holds the default value on creation for the version field.
	session.DefaultVersion = sessionDescVersion.Default.(int64)
	// sessionDescUserVersion is the schema descriptor for user_version field.
	sessionDescUserVersion := sessionFields[7].Descriptor()
	// session.DefaultUserVersion holds the default value on creation for the user_version field.
	session.DefaultUserVersion = sessionDescUserVersion.Default.(int64)
	// sessionDescLastSeenAt is the schema descriptor for last_seen_at field.
	sessionDescLastSeenAt := sessionFields[9].Descriptor()
	// session.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	session.DefaultLastSeenAt = sessionDescLastSeenAt.Default.(func() time.Time)
	// session.UpdateDefaultLastSeenAt holds the default value on update for the last_seen_at field.
	session.UpdateDefaultLastSeenAt = sessionDescLastSeenAt.UpdateDefault.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	ssosessionFields := schema.SsoSession{}.Fields()
	_ = ssosessionFields
	// ssosessionDescSSOTokenHash is the schema descriptor for sso_token_hash field.
	ssosessionDescSSOTokenHash := ssosessionFields[1].Descriptor()
	// ssosession.SSOTokenHashValidator is a validator for the "sso_token_hash" field. It is called by the builders before save.
	ssosession.SSOTokenHashValidator = ssosessionDescSSOTokenHash.Validators[0].(func(string) error)
	// ssosessionDescDeviceID is the schema descriptor for device_id field.
	ssosessionDescDeviceID := ssosessionFields[2].Descriptor()
	// ssosession.DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	ssosession.DeviceIDValidator = ssosessionDescDeviceID.Validators[0].(func(string) error)
	// ssosessionDescUserAgent is the schema descriptor for user_agent field.
	ssosessionDescUserAgent := ssosessionFields[3].Descriptor()
	// ssosession.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	ssosession.UserAgentValidator = ssosessionDescUserAgent.Validators[0].(func(string) error)
	// ssosessionDescSSOVersion is the schema descriptor for sso_version field.
	ssosessionDescSSOVersion := ssosessionFields[6].Descriptor()
	// ssosession.DefaultSSOVersion holds the default value on creation for the sso_version field.
	ssosession.DefaultSSOVersion = ssosessionDescSSOVersion.Default.(int64)
	// ssosessionDescUserVersion is the schema descriptor for user_version field.
	ssosessionDescUserVersion := ssosessionFields[7].Descriptor()
	// ssosession.DefaultUserVersion holds the default value on creation for the user_version field.
	ssosession.DefaultUserVersion = ssosessionDescUserVersion.Default.(int64)
	// ssosessionDescLastSeenAt is the schema descriptor for last_seen_at field.
	ssosessionDescLastSeenAt := ssosessionFields[9].Descriptor()
	// ssosession.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	ssosession.DefaultLastSeenAt = ssosessionDescLastSeenAt.Default.(func() time.Time)
	// ssosession.UpdateDefaultLastSeenAt holds the default value on update for the last_seen_at field.
	ssosession.UpdateDefaultLastSeenAt = ssosessionDescLastSeenAt.UpdateDefault.(func() time.Time)
	// ssosessionDescID is the schema descriptor for id field.
	ssosessionDescID := ssosessionFields[0].Descriptor()
	// ssosession.DefaultID holds the default value on creation for the id field.
	ssosession.DefaultID = ssosessionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUserVersion is the schema descriptor for user_version field.
	userDescUserVersion := userFields[1].Descriptor()
	// user.DefaultUserVersion holds the default value on creation for the user_version field.
	user.DefaultUserVersion = userDescUserVersion.Default.(int64)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int64) error)
	userappauthorizationFields := schema.UserAppAuthorization{}.Fields()
	_ = userappauthorizationFields
	// userappauthorizationDescScopes is the schema descriptor for scopes field.
	userappauthorizationDescScopes := userappauthorizationFields[1].Descriptor()
	// userappauthorization.DefaultScopes holds the default value on creation for the scopes field.
	userappauthorization.DefaultScopes = userappauthorizationDescScopes.Default.([]string)
	// userappauthorizationDescExtProfile is the schema descriptor for ext_profile field.
	userappauthorizationDescExtProfile := userappauthorizationFields[2].Descriptor()
	// userappauthorization.DefaultExtProfile holds the default value on creation for the ext_profile field.
	userappauthorization.DefaultExtProfile = userappauthorizationDescExtProfile.Default.(map[string]interface{})
	// userappauthorizationDescFirstAuthorizedAt is the schema descriptor for first_authorized_at field.
	userappauthorizationDescFirstAuthorizedAt := userappauthorizationFields[3].Descriptor()
	// userappauthorization.DefaultFirstAuthorizedAt holds the default value on creation for the first_authorized_at field.
	userappauthorization.DefaultFirstAuthorizedAt = userappauthorizationDescFirstAuthorizedAt.Default.(func() time.Time)
	// userappauthorizationDescLastActiveAt is the schema descriptor for last_active_at field.
	userappauthorizationDescLastActiveAt := userappauthorizationFields[5].Descriptor()
	// userappauthorization.DefaultLastActiveAt holds the default value on creation for the last_active_at field.
	userappauthorization.DefaultLastActiveAt = userappauthorizationDescLastActiveAt.Default.(func() time.Time)
	// userappauthorization.UpdateDefaultLastActiveAt holds the default value on update for the last_active_at field.
	userappauthorization.UpdateDefaultLastActiveAt = userappauthorizationDescLastActiveAt.UpdateDefault.(func() time.Time)
	useridentityFields := schema.UserIdentity{}.Fields()
	_ = useridentityFields
	// useridentityDescProviderUID is the schema descriptor for provider_uid field.
	useridentityDescProviderUID := useridentityFields[1].Descriptor()
	// useridentity.ProviderUIDValidator is a validator for the "provider_uid" field. It is called by the builders before save.
	useridentity.ProviderUIDValidator = func() func(string) error {
		validators := useridentityDescProviderUID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider_uid string) error {
			for _, fn := range fns {
				if err := fn(provider_uid); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// useridentityDescProviderUnionID is the schema descriptor for provider_union_id field.
	useridentityDescProviderUnionID := useridentityFields[2].Descriptor()
	// useridentity.ProviderUnionIDValidator is a validator for the "provider_union_id" field. It is called by the builders before save.
	useridentity.ProviderUnionIDValidator = useridentityDescProviderUnionID.Validators[0].(func(string) error)
	// useridentityDescLoginName is the schema descriptor for login_name field.
	useridentityDescLoginName := useridentityFields[3].Descriptor()
	// useridentity.LoginNameValidator is a validator for the "login_name" field. It is called by the builders before save.
	useridentity.LoginNameValidator = useridentityDescLoginName.Validators[0].(func(string) error)
	// useridentityDescLinkedAt is the schema descriptor for linked_at field.
	useridentityDescLinkedAt := useridentityFields[6].Descriptor()
	// useridentity.DefaultLinkedAt holds the default value on creation for the linked_at field.
	useridentity.DefaultLinkedAt = useridentityDescLinkedAt.Default.(func() time.Time)
	// useridentityDescMeta is the schema descriptor for meta field.
	useridentityDescMeta := useridentityFields[8].Descriptor()
	// useridentity.DefaultMeta holds the default value on creation for the meta field.
	useridentity.DefaultMeta = useridentityDescMeta.Default.(map[string]interface{})
}
