// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/luckysxx/user-platform/internal/ent/app"
	"github.com/luckysxx/user-platform/internal/ent/session"
	"github.com/luckysxx/user-platform/internal/ent/ssosession"
	"github.com/luckysxx/user-platform/internal/ent/user"
	"github.com/luckysxx/user-platform/internal/ent/useridentity"
)

// Session is the model entity for the Session schema.
type Session struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// 会话令牌哈希（当前主要承载 refresh token 哈希）
	SessionTokenHash string `json:"session_token_hash,omitempty"`
	// 设备标识
	DeviceID *string `json:"device_id,omitempty"`
	// 用户 agent / 客户端标识
	UserAgent *string `json:"user_agent,omitempty"`
	// 客户端 IP
	IP *string `json:"ip,omitempty"`
	// 会话状态
	Status session.Status `json:"status,omitempty"`
	// 当前会话版本，仅影响该 session
	Version int64 `json:"version,omitempty"`
	// 创建该应用会话时的用户全局版本快照
	UserVersion int64 `json:"user_version,omitempty"`
	// 会话过期时间
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// 最近一次心跳时间
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// 撤销时间
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SessionQuery when eager-loading is set.
	Edges                  SessionEdges `json:"edges"`
	app_sessions           *int
	sso_session_sessions   *uuid.UUID
	user_sessions          *int64
	user_identity_sessions *int
	selectValues           sql.SelectValues
}

// SessionEdges holds the relations/edges for other nodes in the graph.
type SessionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// App holds the value of the app edge.
	App *App `json:"app,omitempty"`
	// SSOSession holds the value of the sso_session edge.
	SSOSession *SsoSession `json:"sso_session,omitempty"`
	// Identity holds the value of the identity edge.
	Identity *UserIdentity `json:"identity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SessionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AppOrErr returns the App value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SessionEdges) AppOrErr() (*App, error) {
	if e.App != nil {
		return e.App, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: app.Label}
	}
	return nil, &NotLoadedError{edge: "app"}
}

// SSOSessionOrErr returns the SSOSession value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SessionEdges) SSOSessionOrErr() (*SsoSession, error) {
	if e.SSOSession != nil {
		return e.SSOSession, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: ssosession.Label}
	}
	return nil, &NotLoadedError{edge: "sso_session"}
}

// IdentityOrErr returns the Identity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SessionEdges) IdentityOrErr() (*UserIdentity, error) {
	if e.Identity != nil {
		return e.Identity, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: useridentity.Label}
	}
	return nil, &NotLoadedError{edge: "identity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Session) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case session.FieldVersion, session.FieldUserVersion:
			values[i] = new(sql.NullInt64)
		case session.FieldSessionTokenHash, session.FieldDeviceID, session.FieldUserAgent, session.FieldIP, session.FieldStatus:
			values[i] = new(sql.NullString)
		case session.FieldExpiresAt, session.FieldLastSeenAt, session.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		case session.FieldID:
			values[i] = new(uuid.UUID)
		case session.ForeignKeys[0]: // app_sessions
			values[i] = new(sql.NullInt64)
		case session.ForeignKeys[1]: // sso_session_sessions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case session.ForeignKeys[2]: // user_sessions
			values[i] = new(sql.NullInt64)
		case session.ForeignKeys[3]: // user_identity_sessions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Session fields.
func (_m *Session) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case session.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case session.FieldSessionTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_token_hash", values[i])
			} else if value.Valid {
				_m.SessionTokenHash = value.String
			}
		case session.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = new(string)
				*_m.DeviceID = value.String
			}
		case session.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = new(string)
				*_m.UserAgent = value.String
			}
		case session.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = new(string)
				*_m.IP = value.String
			}
		case session.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = session.Status(value.String)
			}
		case session.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case session.FieldUserVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_version", values[i])
			} else if value.Valid {
				_m.UserVersion = value.Int64
			}
		case session.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case session.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case session.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case session.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field app_sessions", value)
			} else if value.Valid {
				_m.app_sessions = new(int)
				*_m.app_sessions = int(value.Int64)
			}
		case session.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field sso_session_sessions", values[i])
			} else if value.Valid {
				_m.sso_session_sessions = new(uuid.UUID)
				*_m.sso_session_sessions = *value.S.(*uuid.UUID)
			}
		case session.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_sessions", value)
			} else if value.Valid {
				_m.user_sessions = new(int64)
				*_m.user_sessions = int64(value.Int64)
			}
		case session.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_identity_sessions", value)
			} else if value.Valid {
				_m.user_identity_sessions = new(int)
				*_m.user_identity_sessions = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Session.
// This includes values selected through modifiers, order, etc.
func (_m *Session) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Session entity.
func (_m *Session) QueryUser() *UserQuery {
	return NewSessionClient(_m.config).QueryUser(_m)
}

// QueryApp queries the "app" edge of the Session entity.
func (_m *Session) QueryApp() *AppQuery {
	return NewSessionClient(_m.config).QueryApp(_m)
}

// QuerySSOSession queries the "sso_session" edge of the Session entity.
func (_m *Session) QuerySSOSession() *SsoSessionQuery {
	return NewSessionClient(_m.config).QuerySSOSession(_m)
}

// QueryIdentity queries the "identity" edge of the Session entity.
func (_m *Session) QueryIdentity() *UserIdentityQuery {
	return NewSessionClient(_m.config).QueryIdentity(_m)
}

// Update returns a builder for updating this Session.
// Note that you need to call Session.Unwrap() before calling this method if this Session
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Session) Update() *SessionUpdateOne {
	return NewSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Session entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Session) Unwrap() *Session {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Session is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Session) String() string {
	var builder strings.Builder
	builder.WriteString("Session(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_token_hash=")
	builder.WriteString(_m.SessionTokenHash)
	builder.WriteString(", ")
	if v := _m.DeviceID; v != nil {
		builder.WriteString("device_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserAgent; v != nil {
		builder.WriteString("user_agent=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IP; v != nil {
		builder.WriteString("ip=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("user_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserVersion))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Sessions is a parsable slice of Session.
type Sessions []*Session
