// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/user-platform/internal/ent/app"
	"github.com/luckysxx/user-platform/internal/ent/predicate"
	"github.com/luckysxx/user-platform/internal/ent/user"
	"github.com/luckysxx/user-platform/internal/ent/userappprofile"
)

// UserAppProfileUpdate is the builder for updating UserAppProfile entities.
type UserAppProfileUpdate struct {
	config
	hooks    []Hook
	mutation *UserAppProfileMutation
}

// Where appends a list predicates to the UserAppProfileUpdate builder.
func (_u *UserAppProfileUpdate) Where(ps ...predicate.UserAppProfile) *UserAppProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLastActiveAt sets the "last_active_at" field.
func (_u *UserAppProfileUpdate) SetLastActiveAt(v time.Time) *UserAppProfileUpdate {
	_u.mutation.SetLastActiveAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserAppProfileUpdate) SetUserID(id int64) *UserAppProfileUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserAppProfileUpdate) SetUser(v *User) *UserAppProfileUpdate {
	return _u.SetUserID(v.ID)
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *UserAppProfileUpdate) SetAppID(id int) *UserAppProfileUpdate {
	_u.mutation.SetAppID(id)
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *UserAppProfileUpdate) SetApp(v *App) *UserAppProfileUpdate {
	return _u.SetAppID(v.ID)
}

// Mutation returns the UserAppProfileMutation object of the builder.
func (_u *UserAppProfileUpdate) Mutation() *UserAppProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserAppProfileUpdate) ClearUser() *UserAppProfileUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearApp clears the "app" edge to the App entity.
func (_u *UserAppProfileUpdate) ClearApp() *UserAppProfileUpdate {
	_u.mutation.ClearApp()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAppProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAppProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAppProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAppProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAppProfileUpdate) defaults() {
	if _, ok := _u.mutation.LastActiveAt(); !ok {
		v := userappprofile.UpdateDefaultLastActiveAt()
		_u.mutation.SetLastActiveAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAppProfileUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAppProfile.user"`)
	}
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAppProfile.app"`)
	}
	return nil
}

func (_u *UserAppProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userappprofile.Table, userappprofile.Columns, sqlgraph.NewFieldSpec(userappprofile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LastActiveAt(); ok {
		_spec.SetField(userappprofile.FieldLastActiveAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappprofile.UserTable,
			Columns: []string{userappprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappprofile.UserTable,
			Columns: []string{userappprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappprofile.AppTable,
			Columns: []string{userappprofile.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappprofile.AppTable,
			Columns: []string{userappprofile.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userappprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAppProfileUpdateOne is the builder for updating a single UserAppProfile entity.
type UserAppProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAppProfileMutation
}

// SetLastActiveAt sets the "last_active_at" field.
func (_u *UserAppProfileUpdateOne) SetLastActiveAt(v time.Time) *UserAppProfileUpdateOne {
	_u.mutation.SetLastActiveAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserAppProfileUpdateOne) SetUserID(id int64) *UserAppProfileUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserAppProfileUpdateOne) SetUser(v *User) *UserAppProfileUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *UserAppProfileUpdateOne) SetAppID(id int) *UserAppProfileUpdateOne {
	_u.mutation.SetAppID(id)
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *UserAppProfileUpdateOne) SetApp(v *App) *UserAppProfileUpdateOne {
	return _u.SetAppID(v.ID)
}

// Mutation returns the UserAppProfileMutation object of the builder.
func (_u *UserAppProfileUpdateOne) Mutation() *UserAppProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserAppProfileUpdateOne) ClearUser() *UserAppProfileUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearApp clears the "app" edge to the App entity.
func (_u *UserAppProfileUpdateOne) ClearApp() *UserAppProfileUpdateOne {
	_u.mutation.ClearApp()
	return _u
}

// Where appends a list predicates to the UserAppProfileUpdate builder.
func (_u *UserAppProfileUpdateOne) Where(ps ...predicate.UserAppProfile) *UserAppProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAppProfileUpdateOne) Select(field string, fields ...string) *UserAppProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAppProfile entity.
func (_u *UserAppProfileUpdateOne) Save(ctx context.Context) (*UserAppProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAppProfileUpdateOne) SaveX(ctx context.Context) *UserAppProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAppProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAppProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAppProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.LastActiveAt(); !ok {
		v := userappprofile.UpdateDefaultLastActiveAt()
		_u.mutation.SetLastActiveAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAppProfileUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAppProfile.user"`)
	}
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAppProfile.app"`)
	}
	return nil
}

func (_u *UserAppProfileUpdateOne) sqlSave(ctx context.Context) (_node *UserAppProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userappprofile.Table, userappprofile.Columns, sqlgraph.NewFieldSpec(userappprofile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAppProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userappprofile.FieldID)
		for _, f := range fields {
			if !userappprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userappprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LastActiveAt(); ok {
		_spec.SetField(userappprofile.FieldLastActiveAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappprofile.UserTable,
			Columns: []string{userappprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappprofile.UserTable,
			Columns: []string{userappprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappprofile.AppTable,
			Columns: []string{userappprofile.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappprofile.AppTable,
			Columns: []string{userappprofile.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserAppProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userappprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
