// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/luckysxx/user-platform/internal/ent/app"
	"github.com/luckysxx/user-platform/internal/ent/user"
	"github.com/luckysxx/user-platform/internal/ent/userappprofile"
)

// UserAppProfile is the model entity for the UserAppProfile schema.
type UserAppProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// FirstAuthorizedAt holds the value of the "first_authorized_at" field.
	FirstAuthorizedAt time.Time `json:"first_authorized_at,omitempty"`
	// LastActiveAt holds the value of the "last_active_at" field.
	LastActiveAt time.Time `json:"last_active_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserAppProfileQuery when eager-loading is set.
	Edges         UserAppProfileEdges `json:"edges"`
	app_profiles  *int
	user_profiles *int64
	selectValues  sql.SelectValues
}

// UserAppProfileEdges holds the relations/edges for other nodes in the graph.
type UserAppProfileEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// App holds the value of the app edge.
	App *App `json:"app,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserAppProfileEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AppOrErr returns the App value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserAppProfileEdges) AppOrErr() (*App, error) {
	if e.App != nil {
		return e.App, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: app.Label}
	}
	return nil, &NotLoadedError{edge: "app"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAppProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userappprofile.FieldID:
			values[i] = new(sql.NullInt64)
		case userappprofile.FieldFirstAuthorizedAt, userappprofile.FieldLastActiveAt:
			values[i] = new(sql.NullTime)
		case userappprofile.ForeignKeys[0]: // app_profiles
			values[i] = new(sql.NullInt64)
		case userappprofile.ForeignKeys[1]: // user_profiles
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAppProfile fields.
func (_m *UserAppProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userappprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userappprofile.FieldFirstAuthorizedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_authorized_at", values[i])
			} else if value.Valid {
				_m.FirstAuthorizedAt = value.Time
			}
		case userappprofile.FieldLastActiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_active_at", values[i])
			} else if value.Valid {
				_m.LastActiveAt = value.Time
			}
		case userappprofile.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field app_profiles", value)
			} else if value.Valid {
				_m.app_profiles = new(int)
				*_m.app_profiles = int(value.Int64)
			}
		case userappprofile.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_profiles", value)
			} else if value.Valid {
				_m.user_profiles = new(int64)
				*_m.user_profiles = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAppProfile.
// This includes values selected through modifiers, order, etc.
func (_m *UserAppProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserAppProfile entity.
func (_m *UserAppProfile) QueryUser() *UserQuery {
	return NewUserAppProfileClient(_m.config).QueryUser(_m)
}

// QueryApp queries the "app" edge of the UserAppProfile entity.
func (_m *UserAppProfile) QueryApp() *AppQuery {
	return NewUserAppProfileClient(_m.config).QueryApp(_m)
}

// Update returns a builder for updating this UserAppProfile.
// Note that you need to call UserAppProfile.Unwrap() before calling this method if this UserAppProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserAppProfile) Update() *UserAppProfileUpdateOne {
	return NewUserAppProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserAppProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserAppProfile) Unwrap() *UserAppProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAppProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserAppProfile) String() string {
	var builder strings.Builder
	builder.WriteString("UserAppProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("first_authorized_at=")
	builder.WriteString(_m.FirstAuthorizedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_active_at=")
	builder.WriteString(_m.LastActiveAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserAppProfiles is a parsable slice of UserAppProfile.
type UserAppProfiles []*UserAppProfile
