// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/luckysxx/user-platform/internal/ent/app"
	"github.com/luckysxx/user-platform/internal/ent/user"
	"github.com/luckysxx/user-platform/internal/ent/userappauthorization"
	"github.com/luckysxx/user-platform/internal/ent/useridentity"
)

// UserAppAuthorization is the model entity for the UserAppAuthorization schema.
type UserAppAuthorization struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 授权状态
	Status userappauthorization.Status `json:"status,omitempty"`
	// 授权范围
	Scopes []string `json:"scopes,omitempty"`
	// 应用级扩展资料
	ExtProfile map[string]interface{} `json:"ext_profile,omitempty"`
	// 首次授权时间
	FirstAuthorizedAt time.Time `json:"first_authorized_at,omitempty"`
	// 最近一次登录时间
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`
	// 最近一次活跃时间
	LastActiveAt time.Time `json:"last_active_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserAppAuthorizationQuery when eager-loading is set.
	Edges                        UserAppAuthorizationEdges `json:"edges"`
	app_authorizations           *int
	user_authorizations          *int64
	user_identity_authorizations *int
	selectValues                 sql.SelectValues
}

// UserAppAuthorizationEdges holds the relations/edges for other nodes in the graph.
type UserAppAuthorizationEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// App holds the value of the app edge.
	App *App `json:"app,omitempty"`
	// SourceIdentity holds the value of the source_identity edge.
	SourceIdentity *UserIdentity `json:"source_identity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserAppAuthorizationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AppOrErr returns the App value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserAppAuthorizationEdges) AppOrErr() (*App, error) {
	if e.App != nil {
		return e.App, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: app.Label}
	}
	return nil, &NotLoadedError{edge: "app"}
}

// SourceIdentityOrErr returns the SourceIdentity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserAppAuthorizationEdges) SourceIdentityOrErr() (*UserIdentity, error) {
	if e.SourceIdentity != nil {
		return e.SourceIdentity, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: useridentity.Label}
	}
	return nil, &NotLoadedError{edge: "source_identity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAppAuthorization) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userappauthorization.FieldScopes, userappauthorization.FieldExtProfile:
			values[i] = new([]byte)
		case userappauthorization.FieldID:
			values[i] = new(sql.NullInt64)
		case userappauthorization.FieldStatus:
			values[i] = new(sql.NullString)
		case userappauthorization.FieldFirstAuthorizedAt, userappauthorization.FieldLastLoginAt, userappauthorization.FieldLastActiveAt:
			values[i] = new(sql.NullTime)
		case userappauthorization.ForeignKeys[0]: // app_authorizations
			values[i] = new(sql.NullInt64)
		case userappauthorization.ForeignKeys[1]: // user_authorizations
			values[i] = new(sql.NullInt64)
		case userappauthorization.ForeignKeys[2]: // user_identity_authorizations
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAppAuthorization fields.
func (_m *UserAppAuthorization) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userappauthorization.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userappauthorization.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = userappauthorization.Status(value.String)
			}
		case userappauthorization.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case userappauthorization.FieldExtProfile:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ext_profile", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtProfile); err != nil {
					return fmt.Errorf("unmarshal field ext_profile: %w", err)
				}
			}
		case userappauthorization.FieldFirstAuthorizedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_authorized_at", values[i])
			} else if value.Valid {
				_m.FirstAuthorizedAt = value.Time
			}
		case userappauthorization.FieldLastLoginAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login_at", values[i])
			} else if value.Valid {
				_m.LastLoginAt = new(time.Time)
				*_m.LastLoginAt = value.Time
			}
		case userappauthorization.FieldLastActiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_active_at", values[i])
			} else if value.Valid {
				_m.LastActiveAt = value.Time
			}
		case userappauthorization.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field app_authorizations", value)
			} else if value.Valid {
				_m.app_authorizations = new(int)
				*_m.app_authorizations = int(value.Int64)
			}
		case userappauthorization.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_authorizations", value)
			} else if value.Valid {
				_m.user_authorizations = new(int64)
				*_m.user_authorizations = int64(value.Int64)
			}
		case userappauthorization.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_identity_authorizations", value)
			} else if value.Valid {
				_m.user_identity_authorizations = new(int)
				*_m.user_identity_authorizations = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAppAuthorization.
// This includes values selected through modifiers, order, etc.
func (_m *UserAppAuthorization) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserAppAuthorization entity.
func (_m *UserAppAuthorization) QueryUser() *UserQuery {
	return NewUserAppAuthorizationClient(_m.config).QueryUser(_m)
}

// QueryApp queries the "app" edge of the UserAppAuthorization entity.
func (_m *UserAppAuthorization) QueryApp() *AppQuery {
	return NewUserAppAuthorizationClient(_m.config).QueryApp(_m)
}

// QuerySourceIdentity queries the "source_identity" edge of the UserAppAuthorization entity.
func (_m *UserAppAuthorization) QuerySourceIdentity() *UserIdentityQuery {
	return NewUserAppAuthorizationClient(_m.config).QuerySourceIdentity(_m)
}

// Update returns a builder for updating this UserAppAuthorization.
// Note that you need to call UserAppAuthorization.Unwrap() before calling this method if this UserAppAuthorization
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserAppAuthorization) Update() *UserAppAuthorizationUpdateOne {
	return NewUserAppAuthorizationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserAppAuthorization entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserAppAuthorization) Unwrap() *UserAppAuthorization {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAppAuthorization is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserAppAuthorization) String() string {
	var builder strings.Builder
	builder.WriteString("UserAppAuthorization(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scopes))
	builder.WriteString(", ")
	builder.WriteString("ext_profile=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtProfile))
	builder.WriteString(", ")
	builder.WriteString("first_authorized_at=")
	builder.WriteString(_m.FirstAuthorizedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastLoginAt; v != nil {
		builder.WriteString("last_login_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_active_at=")
	builder.WriteString(_m.LastActiveAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserAppAuthorizations is a parsable slice of UserAppAuthorization.
type UserAppAuthorizations []*UserAppAuthorization
