// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/user-platform/internal/ent/app"
	"github.com/luckysxx/user-platform/internal/ent/predicate"
	"github.com/luckysxx/user-platform/internal/ent/user"
	"github.com/luckysxx/user-platform/internal/ent/userappauthorization"
	"github.com/luckysxx/user-platform/internal/ent/useridentity"
)

// UserAppAuthorizationQuery is the builder for querying UserAppAuthorization entities.
type UserAppAuthorizationQuery struct {
	config
	ctx                *QueryContext
	order              []userappauthorization.OrderOption
	inters             []Interceptor
	predicates         []predicate.UserAppAuthorization
	withUser           *UserQuery
	withApp            *AppQuery
	withSourceIdentity *UserIdentityQuery
	withFKs            bool
	modifiers          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserAppAuthorizationQuery builder.
func (_q *UserAppAuthorizationQuery) Where(ps ...predicate.UserAppAuthorization) *UserAppAuthorizationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UserAppAuthorizationQuery) Limit(limit int) *UserAppAuthorizationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UserAppAuthorizationQuery) Offset(offset int) *UserAppAuthorizationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UserAppAuthorizationQuery) Unique(unique bool) *UserAppAuthorizationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UserAppAuthorizationQuery) Order(o ...userappauthorization.OrderOption) *UserAppAuthorizationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *UserAppAuthorizationQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userappauthorization.Table, userappauthorization.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userappauthorization.UserTable, userappauthorization.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryApp chains the current query on the "app" edge.
func (_q *UserAppAuthorizationQuery) QueryApp() *AppQuery {
	query := (&AppClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userappauthorization.Table, userappauthorization.FieldID, selector),
			sqlgraph.To(app.Table, app.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userappauthorization.AppTable, userappauthorization.AppColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySourceIdentity chains the current query on the "source_identity" edge.
func (_q *UserAppAuthorizationQuery) QuerySourceIdentity() *UserIdentityQuery {
	query := (&UserIdentityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userappauthorization.Table, userappauthorization.FieldID, selector),
			sqlgraph.To(useridentity.Table, useridentity.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userappauthorization.SourceIdentityTable, userappauthorization.SourceIdentityColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserAppAuthorization entity from the query.
// Returns a *NotFoundError when no UserAppAuthorization was found.
func (_q *UserAppAuthorizationQuery) First(ctx context.Context) (*UserAppAuthorization, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userappauthorization.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UserAppAuthorizationQuery) FirstX(ctx context.Context) *UserAppAuthorization {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserAppAuthorization ID from the query.
// Returns a *NotFoundError when no UserAppAuthorization ID was found.
func (_q *UserAppAuthorizationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userappauthorization.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UserAppAuthorizationQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserAppAuthorization entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserAppAuthorization entity is found.
// Returns a *NotFoundError when no UserAppAuthorization entities are found.
func (_q *UserAppAuthorizationQuery) Only(ctx context.Context) (*UserAppAuthorization, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userappauthorization.Label}
	default:
		return nil, &NotSingularError{userappauthorization.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UserAppAuthorizationQuery) OnlyX(ctx context.Context) *UserAppAuthorization {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserAppAuthorization ID in the query.
// Returns a *NotSingularError when more than one UserAppAuthorization ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UserAppAuthorizationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userappauthorization.Label}
	default:
		err = &NotSingularError{userappauthorization.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UserAppAuthorizationQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserAppAuthorizations.
func (_q *UserAppAuthorizationQuery) All(ctx context.Context) ([]*UserAppAuthorization, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserAppAuthorization, *UserAppAuthorizationQuery]()
	return withInterceptors[[]*UserAppAuthorization](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UserAppAuthorizationQuery) AllX(ctx context.Context) []*UserAppAuthorization {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserAppAuthorization IDs.
func (_q *UserAppAuthorizationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(userappauthorization.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UserAppAuthorizationQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UserAppAuthorizationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UserAppAuthorizationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UserAppAuthorizationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UserAppAuthorizationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UserAppAuthorizationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserAppAuthorizationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UserAppAuthorizationQuery) Clone() *UserAppAuthorizationQuery {
	if _q == nil {
		return nil
	}
	return &UserAppAuthorizationQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]userappauthorization.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.UserAppAuthorization{}, _q.predicates...),
		withUser:           _q.withUser.Clone(),
		withApp:            _q.withApp.Clone(),
		withSourceIdentity: _q.withSourceIdentity.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserAppAuthorizationQuery) WithUser(opts ...func(*UserQuery)) *UserAppAuthorizationQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithApp tells the query-builder to eager-load the nodes that are connected to
// the "app" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserAppAuthorizationQuery) WithApp(opts ...func(*AppQuery)) *UserAppAuthorizationQuery {
	query := (&AppClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withApp = query
	return _q
}

// WithSourceIdentity tells the query-builder to eager-load the nodes that are connected to
// the "source_identity" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserAppAuthorizationQuery) WithSourceIdentity(opts ...func(*UserIdentityQuery)) *UserAppAuthorizationQuery {
	query := (&UserIdentityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSourceIdentity = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status userappauthorization.Status `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserAppAuthorization.Query().
//		GroupBy(userappauthorization.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UserAppAuthorizationQuery) GroupBy(field string, fields ...string) *UserAppAuthorizationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserAppAuthorizationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = userappauthorization.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status userappauthorization.Status `json:"status,omitempty"`
//	}
//
//	client.UserAppAuthorization.Query().
//		Select(userappauthorization.FieldStatus).
//		Scan(ctx, &v)
func (_q *UserAppAuthorizationQuery) Select(fields ...string) *UserAppAuthorizationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UserAppAuthorizationSelect{UserAppAuthorizationQuery: _q}
	sbuild.label = userappauthorization.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserAppAuthorizationSelect configured with the given aggregations.
func (_q *UserAppAuthorizationQuery) Aggregate(fns ...AggregateFunc) *UserAppAuthorizationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UserAppAuthorizationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !userappauthorization.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *UserAppAuthorizationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserAppAuthorization, error) {
	var (
		nodes       = []*UserAppAuthorization{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUser != nil,
			_q.withApp != nil,
			_q.withSourceIdentity != nil,
		}
	)
	if _q.withUser != nil || _q.withApp != nil || _q.withSourceIdentity != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, userappauthorization.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserAppAuthorization).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserAppAuthorization{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *UserAppAuthorization, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withApp; query != nil {
		if err := _q.loadApp(ctx, query, nodes, nil,
			func(n *UserAppAuthorization, e *App) { n.Edges.App = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSourceIdentity; query != nil {
		if err := _q.loadSourceIdentity(ctx, query, nodes, nil,
			func(n *UserAppAuthorization, e *UserIdentity) { n.Edges.SourceIdentity = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UserAppAuthorizationQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserAppAuthorization, init func(*UserAppAuthorization), assign func(*UserAppAuthorization, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UserAppAuthorization)
	for i := range nodes {
		if nodes[i].user_authorizations == nil {
			continue
		}
		fk := *nodes[i].user_authorizations
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_authorizations" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *UserAppAuthorizationQuery) loadApp(ctx context.Context, query *AppQuery, nodes []*UserAppAuthorization, init func(*UserAppAuthorization), assign func(*UserAppAuthorization, *App)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UserAppAuthorization)
	for i := range nodes {
		if nodes[i].app_authorizations == nil {
			continue
		}
		fk := *nodes[i].app_authorizations
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(app.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "app_authorizations" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *UserAppAuthorizationQuery) loadSourceIdentity(ctx context.Context, query *UserIdentityQuery, nodes []*UserAppAuthorization, init func(*UserAppAuthorization), assign func(*UserAppAuthorization, *UserIdentity)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UserAppAuthorization)
	for i := range nodes {
		if nodes[i].user_identity_authorizations == nil {
			continue
		}
		fk := *nodes[i].user_identity_authorizations
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(useridentity.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_identity_authorizations" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *UserAppAuthorizationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UserAppAuthorizationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userappauthorization.Table, userappauthorization.Columns, sqlgraph.NewFieldSpec(userappauthorization.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userappauthorization.FieldID)
		for i := range fields {
			if fields[i] != userappauthorization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UserAppAuthorizationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(userappauthorization.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = userappauthorization.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *UserAppAuthorizationQuery) ForUpdate(opts ...sql.LockOption) *UserAppAuthorizationQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *UserAppAuthorizationQuery) ForShare(opts ...sql.LockOption) *UserAppAuthorizationQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// UserAppAuthorizationGroupBy is the group-by builder for UserAppAuthorization entities.
type UserAppAuthorizationGroupBy struct {
	selector
	build *UserAppAuthorizationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UserAppAuthorizationGroupBy) Aggregate(fns ...AggregateFunc) *UserAppAuthorizationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UserAppAuthorizationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserAppAuthorizationQuery, *UserAppAuthorizationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UserAppAuthorizationGroupBy) sqlScan(ctx context.Context, root *UserAppAuthorizationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserAppAuthorizationSelect is the builder for selecting fields of UserAppAuthorization entities.
type UserAppAuthorizationSelect struct {
	*UserAppAuthorizationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UserAppAuthorizationSelect) Aggregate(fns ...AggregateFunc) *UserAppAuthorizationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UserAppAuthorizationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserAppAuthorizationQuery, *UserAppAuthorizationSelect](ctx, _s.UserAppAuthorizationQuery, _s, _s.inters, v)
}

func (_s *UserAppAuthorizationSelect) sqlScan(ctx context.Context, root *UserAppAuthorizationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
