// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luckysxx/user-platform/internal/ent/app"
	"github.com/luckysxx/user-platform/internal/ent/user"
	"github.com/luckysxx/user-platform/internal/ent/userappauthorization"
	"github.com/luckysxx/user-platform/internal/ent/useridentity"
)

// UserAppAuthorizationCreate is the builder for creating a UserAppAuthorization entity.
type UserAppAuthorizationCreate struct {
	config
	mutation *UserAppAuthorizationMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *UserAppAuthorizationCreate) SetStatus(v userappauthorization.Status) *UserAppAuthorizationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserAppAuthorizationCreate) SetNillableStatus(v *userappauthorization.Status) *UserAppAuthorizationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *UserAppAuthorizationCreate) SetScopes(v []string) *UserAppAuthorizationCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetExtProfile sets the "ext_profile" field.
func (_c *UserAppAuthorizationCreate) SetExtProfile(v map[string]interface{}) *UserAppAuthorizationCreate {
	_c.mutation.SetExtProfile(v)
	return _c
}

// SetFirstAuthorizedAt sets the "first_authorized_at" field.
func (_c *UserAppAuthorizationCreate) SetFirstAuthorizedAt(v time.Time) *UserAppAuthorizationCreate {
	_c.mutation.SetFirstAuthorizedAt(v)
	return _c
}

// SetNillableFirstAuthorizedAt sets the "first_authorized_at" field if the given value is not nil.
func (_c *UserAppAuthorizationCreate) SetNillableFirstAuthorizedAt(v *time.Time) *UserAppAuthorizationCreate {
	if v != nil {
		_c.SetFirstAuthorizedAt(*v)
	}
	return _c
}

// SetLastLoginAt sets the "last_login_at" field.
func (_c *UserAppAuthorizationCreate) SetLastLoginAt(v time.Time) *UserAppAuthorizationCreate {
	_c.mutation.SetLastLoginAt(v)
	return _c
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_c *UserAppAuthorizationCreate) SetNillableLastLoginAt(v *time.Time) *UserAppAuthorizationCreate {
	if v != nil {
		_c.SetLastLoginAt(*v)
	}
	return _c
}

// SetLastActiveAt sets the "last_active_at" field.
func (_c *UserAppAuthorizationCreate) SetLastActiveAt(v time.Time) *UserAppAuthorizationCreate {
	_c.mutation.SetLastActiveAt(v)
	return _c
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_c *UserAppAuthorizationCreate) SetNillableLastActiveAt(v *time.Time) *UserAppAuthorizationCreate {
	if v != nil {
		_c.SetLastActiveAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *UserAppAuthorizationCreate) SetUserID(id int64) *UserAppAuthorizationCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserAppAuthorizationCreate) SetUser(v *User) *UserAppAuthorizationCreate {
	return _c.SetUserID(v.ID)
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_c *UserAppAuthorizationCreate) SetAppID(id int) *UserAppAuthorizationCreate {
	_c.mutation.SetAppID(id)
	return _c
}

// SetApp sets the "app" edge to the App entity.
func (_c *UserAppAuthorizationCreate) SetApp(v *App) *UserAppAuthorizationCreate {
	return _c.SetAppID(v.ID)
}

// SetSourceIdentityID sets the "source_identity" edge to the UserIdentity entity by ID.
func (_c *UserAppAuthorizationCreate) SetSourceIdentityID(id int) *UserAppAuthorizationCreate {
	_c.mutation.SetSourceIdentityID(id)
	return _c
}

// SetNillableSourceIdentityID sets the "source_identity" edge to the UserIdentity entity by ID if the given value is not nil.
func (_c *UserAppAuthorizationCreate) SetNillableSourceIdentityID(id *int) *UserAppAuthorizationCreate {
	if id != nil {
		_c = _c.SetSourceIdentityID(*id)
	}
	return _c
}

// SetSourceIdentity sets the "source_identity" edge to the UserIdentity entity.
func (_c *UserAppAuthorizationCreate) SetSourceIdentity(v *UserIdentity) *UserAppAuthorizationCreate {
	return _c.SetSourceIdentityID(v.ID)
}

// Mutation returns the UserAppAuthorizationMutation object of the builder.
func (_c *UserAppAuthorizationCreate) Mutation() *UserAppAuthorizationMutation {
	return _c.mutation
}

// Save creates the UserAppAuthorization in the database.
func (_c *UserAppAuthorizationCreate) Save(ctx context.Context) (*UserAppAuthorization, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAppAuthorizationCreate) SaveX(ctx context.Context) *UserAppAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAppAuthorizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAppAuthorizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAppAuthorizationCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := userappauthorization.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := userappauthorization.DefaultScopes
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.ExtProfile(); !ok {
		v := userappauthorization.DefaultExtProfile
		_c.mutation.SetExtProfile(v)
	}
	if _, ok := _c.mutation.FirstAuthorizedAt(); !ok {
		v := userappauthorization.DefaultFirstAuthorizedAt()
		_c.mutation.SetFirstAuthorizedAt(v)
	}
	if _, ok := _c.mutation.LastActiveAt(); !ok {
		v := userappauthorization.DefaultLastActiveAt()
		_c.mutation.SetLastActiveAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAppAuthorizationCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserAppAuthorization.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := userappauthorization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserAppAuthorization.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "UserAppAuthorization.scopes"`)}
	}
	if _, ok := _c.mutation.ExtProfile(); !ok {
		return &ValidationError{Name: "ext_profile", err: errors.New(`ent: missing required field "UserAppAuthorization.ext_profile"`)}
	}
	if _, ok := _c.mutation.FirstAuthorizedAt(); !ok {
		return &ValidationError{Name: "first_authorized_at", err: errors.New(`ent: missing required field "UserAppAuthorization.first_authorized_at"`)}
	}
	if _, ok := _c.mutation.LastActiveAt(); !ok {
		return &ValidationError{Name: "last_active_at", err: errors.New(`ent: missing required field "UserAppAuthorization.last_active_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserAppAuthorization.user"`)}
	}
	if len(_c.mutation.AppIDs()) == 0 {
		return &ValidationError{Name: "app", err: errors.New(`ent: missing required edge "UserAppAuthorization.app"`)}
	}
	return nil
}

func (_c *UserAppAuthorizationCreate) sqlSave(ctx context.Context) (*UserAppAuthorization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAppAuthorizationCreate) createSpec() (*UserAppAuthorization, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAppAuthorization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userappauthorization.Table, sqlgraph.NewFieldSpec(userappauthorization.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userappauthorization.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(userappauthorization.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.ExtProfile(); ok {
		_spec.SetField(userappauthorization.FieldExtProfile, field.TypeJSON, value)
		_node.ExtProfile = value
	}
	if value, ok := _c.mutation.FirstAuthorizedAt(); ok {
		_spec.SetField(userappauthorization.FieldFirstAuthorizedAt, field.TypeTime, value)
		_node.FirstAuthorizedAt = value
	}
	if value, ok := _c.mutation.LastLoginAt(); ok {
		_spec.SetField(userappauthorization.FieldLastLoginAt, field.TypeTime, value)
		_node.LastLoginAt = &value
	}
	if value, ok := _c.mutation.LastActiveAt(); ok {
		_spec.SetField(userappauthorization.FieldLastActiveAt, field.TypeTime, value)
		_node.LastActiveAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappauthorization.UserTable,
			Columns: []string{userappauthorization.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_authorizations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappauthorization.AppTable,
			Columns: []string{userappauthorization.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.app_authorizations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceIdentityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userappauthorization.SourceIdentityTable,
			Columns: []string{userappauthorization.SourceIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_identity_authorizations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserAppAuthorizationCreateBulk is the builder for creating many UserAppAuthorization entities in bulk.
type UserAppAuthorizationCreateBulk struct {
	config
	err      error
	builders []*UserAppAuthorizationCreate
}

// Save creates the UserAppAuthorization entities in the database.
func (_c *UserAppAuthorizationCreateBulk) Save(ctx context.Context) ([]*UserAppAuthorization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAppAuthorization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAppAuthorizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAppAuthorizationCreateBulk) SaveX(ctx context.Context) []*UserAppAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAppAuthorizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAppAuthorizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
