// Code generated by ent, DO NOT EDIT.

package eventoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the eventoutbox type in the database.
	Label = "event_outbox"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAggregatetype holds the string denoting the aggregatetype field in the database.
	FieldAggregatetype = "aggregatetype"
	// FieldAggregateid holds the string denoting the aggregateid field in the database.
	FieldAggregateid = "aggregateid"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldHeaders holds the string denoting the headers field in the database.
	FieldHeaders = "headers"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the eventoutbox in the database.
	Table = "event_outboxes"
)

// Columns holds all SQL columns for eventoutbox fields.
var Columns = []string{
	FieldID,
	FieldAggregatetype,
	FieldAggregateid,
	FieldType,
	FieldPayload,
	FieldHeaders,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the EventOutbox queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAggregatetype orders the results by the aggregatetype field.
func ByAggregatetype(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAggregatetype, opts...).ToFunc()
}

// ByAggregateid orders the results by the aggregateid field.
func ByAggregateid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAggregateid, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
