// Code generated by ent, DO NOT EDIT.

package eventoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/luckysxx/user-platform/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldLTE(FieldID, id))
}

// Aggregatetype applies equality check predicate on the "aggregatetype" field. It's identical to AggregatetypeEQ.
func Aggregatetype(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEQ(FieldAggregatetype, v))
}

// Aggregateid applies equality check predicate on the "aggregateid" field. It's identical to AggregateidEQ.
func Aggregateid(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEQ(FieldAggregateid, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEQ(FieldType, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEQ(FieldCreatedAt, v))
}

// AggregatetypeEQ applies the EQ predicate on the "aggregatetype" field.
func AggregatetypeEQ(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEQ(FieldAggregatetype, v))
}

// AggregatetypeNEQ applies the NEQ predicate on the "aggregatetype" field.
func AggregatetypeNEQ(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNEQ(FieldAggregatetype, v))
}

// AggregatetypeIn applies the In predicate on the "aggregatetype" field.
func AggregatetypeIn(vs ...string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldIn(FieldAggregatetype, vs...))
}

// AggregatetypeNotIn applies the NotIn predicate on the "aggregatetype" field.
func AggregatetypeNotIn(vs ...string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNotIn(FieldAggregatetype, vs...))
}

// AggregatetypeGT applies the GT predicate on the "aggregatetype" field.
func AggregatetypeGT(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldGT(FieldAggregatetype, v))
}

// AggregatetypeGTE applies the GTE predicate on the "aggregatetype" field.
func AggregatetypeGTE(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldGTE(FieldAggregatetype, v))
}

// AggregatetypeLT applies the LT predicate on the "aggregatetype" field.
func AggregatetypeLT(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldLT(FieldAggregatetype, v))
}

// AggregatetypeLTE applies the LTE predicate on the "aggregatetype" field.
func AggregatetypeLTE(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldLTE(FieldAggregatetype, v))
}

// AggregatetypeContains applies the Contains predicate on the "aggregatetype" field.
func AggregatetypeContains(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldContains(FieldAggregatetype, v))
}

// AggregatetypeHasPrefix applies the HasPrefix predicate on the "aggregatetype" field.
func AggregatetypeHasPrefix(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldHasPrefix(FieldAggregatetype, v))
}

// AggregatetypeHasSuffix applies the HasSuffix predicate on the "aggregatetype" field.
func AggregatetypeHasSuffix(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldHasSuffix(FieldAggregatetype, v))
}

// AggregatetypeIsNil applies the IsNil predicate on the "aggregatetype" field.
func AggregatetypeIsNil() predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldIsNull(FieldAggregatetype))
}

// AggregatetypeNotNil applies the NotNil predicate on the "aggregatetype" field.
func AggregatetypeNotNil() predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNotNull(FieldAggregatetype))
}

// AggregatetypeEqualFold applies the EqualFold predicate on the "aggregatetype" field.
func AggregatetypeEqualFold(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEqualFold(FieldAggregatetype, v))
}

// AggregatetypeContainsFold applies the ContainsFold predicate on the "aggregatetype" field.
func AggregatetypeContainsFold(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldContainsFold(FieldAggregatetype, v))
}

// AggregateidEQ applies the EQ predicate on the "aggregateid" field.
func AggregateidEQ(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEQ(FieldAggregateid, v))
}

// AggregateidNEQ applies the NEQ predicate on the "aggregateid" field.
func AggregateidNEQ(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNEQ(FieldAggregateid, v))
}

// AggregateidIn applies the In predicate on the "aggregateid" field.
func AggregateidIn(vs ...string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldIn(FieldAggregateid, vs...))
}

// AggregateidNotIn applies the NotIn predicate on the "aggregateid" field.
func AggregateidNotIn(vs ...string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNotIn(FieldAggregateid, vs...))
}

// AggregateidGT applies the GT predicate on the "aggregateid" field.
func AggregateidGT(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldGT(FieldAggregateid, v))
}

// AggregateidGTE applies the GTE predicate on the "aggregateid" field.
func AggregateidGTE(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldGTE(FieldAggregateid, v))
}

// AggregateidLT applies the LT predicate on the "aggregateid" field.
func AggregateidLT(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldLT(FieldAggregateid, v))
}

// AggregateidLTE applies the LTE predicate on the "aggregateid" field.
func AggregateidLTE(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldLTE(FieldAggregateid, v))
}

// AggregateidContains applies the Contains predicate on the "aggregateid" field.
func AggregateidContains(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldContains(FieldAggregateid, v))
}

// AggregateidHasPrefix applies the HasPrefix predicate on the "aggregateid" field.
func AggregateidHasPrefix(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldHasPrefix(FieldAggregateid, v))
}

// AggregateidHasSuffix applies the HasSuffix predicate on the "aggregateid" field.
func AggregateidHasSuffix(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldHasSuffix(FieldAggregateid, v))
}

// AggregateidIsNil applies the IsNil predicate on the "aggregateid" field.
func AggregateidIsNil() predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldIsNull(FieldAggregateid))
}

// AggregateidNotNil applies the NotNil predicate on the "aggregateid" field.
func AggregateidNotNil() predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNotNull(FieldAggregateid))
}

// AggregateidEqualFold applies the EqualFold predicate on the "aggregateid" field.
func AggregateidEqualFold(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEqualFold(FieldAggregateid, v))
}

// AggregateidContainsFold applies the ContainsFold predicate on the "aggregateid" field.
func AggregateidContainsFold(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldContainsFold(FieldAggregateid, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldHasSuffix(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNotNull(FieldType))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldContainsFold(FieldType, v))
}

// HeadersIsNil applies the IsNil predicate on the "headers" field.
func HeadersIsNil() predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldIsNull(FieldHeaders))
}

// HeadersNotNil applies the NotNil predicate on the "headers" field.
func HeadersNotNil() predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNotNull(FieldHeaders))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EventOutbox {
	return predicate.EventOutbox(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EventOutbox) predicate.EventOutbox {
	return predicate.EventOutbox(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EventOutbox) predicate.EventOutbox {
	return predicate.EventOutbox(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EventOutbox) predicate.EventOutbox {
	return predicate.EventOutbox(sql.NotPredicates(p))
}
