// Code generated by ent, DO NOT EDIT.

package app

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the app type in the database.
	Label = "app"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAppCode holds the string denoting the app_code field in the database.
	FieldAppCode = "app_code"
	// FieldAppName holds the string denoting the app_name field in the database.
	FieldAppName = "app_name"
	// EdgeAuthorizations holds the string denoting the authorizations edge name in mutations.
	EdgeAuthorizations = "authorizations"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// Table holds the table name of the app in the database.
	Table = "apps"
	// AuthorizationsTable is the table that holds the authorizations relation/edge.
	AuthorizationsTable = "user_app_authorizations"
	// AuthorizationsInverseTable is the table name for the UserAppAuthorization entity.
	// It exists in this package in order to avoid circular dependency with the "userappauthorization" package.
	AuthorizationsInverseTable = "user_app_authorizations"
	// AuthorizationsColumn is the table column denoting the authorizations relation/edge.
	AuthorizationsColumn = "app_authorizations"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "sessions"
	// SessionsInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionsInverseTable = "sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "app_sessions"
)

// Columns holds all SQL columns for app fields.
var Columns = []string{
	FieldID,
	FieldAppCode,
	FieldAppName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AppCodeValidator is a validator for the "app_code" field. It is called by the builders before save.
	AppCodeValidator func(string) error
	// AppNameValidator is a validator for the "app_name" field. It is called by the builders before save.
	AppNameValidator func(string) error
)

// OrderOption defines the ordering options for the App queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAppCode orders the results by the app_code field.
func ByAppCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppCode, opts...).ToFunc()
}

// ByAppName orders the results by the app_name field.
func ByAppName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppName, opts...).ToFunc()
}

// ByAuthorizationsCount orders the results by authorizations count.
func ByAuthorizationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuthorizationsStep(), opts...)
	}
}

// ByAuthorizations orders the results by authorizations terms.
func ByAuthorizations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthorizationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAuthorizationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorizationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AuthorizationsTable, AuthorizationsColumn),
	)
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
