// Code generated by ent, DO NOT EDIT.

package app

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/luckysxx/user-platform/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.App {
	return predicate.App(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.App {
	return predicate.App(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.App {
	return predicate.App(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.App {
	return predicate.App(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.App {
	return predicate.App(sql.FieldLTE(FieldID, id))
}

// AppCode applies equality check predicate on the "app_code" field. It's identical to AppCodeEQ.
func AppCode(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldAppCode, v))
}

// AppName applies equality check predicate on the "app_name" field. It's identical to AppNameEQ.
func AppName(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldAppName, v))
}

// AppCodeEQ applies the EQ predicate on the "app_code" field.
func AppCodeEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldAppCode, v))
}

// AppCodeNEQ applies the NEQ predicate on the "app_code" field.
func AppCodeNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldAppCode, v))
}

// AppCodeIn applies the In predicate on the "app_code" field.
func AppCodeIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldAppCode, vs...))
}

// AppCodeNotIn applies the NotIn predicate on the "app_code" field.
func AppCodeNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldAppCode, vs...))
}

// AppCodeGT applies the GT predicate on the "app_code" field.
func AppCodeGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldAppCode, v))
}

// AppCodeGTE applies the GTE predicate on the "app_code" field.
func AppCodeGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldAppCode, v))
}

// AppCodeLT applies the LT predicate on the "app_code" field.
func AppCodeLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldAppCode, v))
}

// AppCodeLTE applies the LTE predicate on the "app_code" field.
func AppCodeLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldAppCode, v))
}

// AppCodeContains applies the Contains predicate on the "app_code" field.
func AppCodeContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldAppCode, v))
}

// AppCodeHasPrefix applies the HasPrefix predicate on the "app_code" field.
func AppCodeHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldAppCode, v))
}

// AppCodeHasSuffix applies the HasSuffix predicate on the "app_code" field.
func AppCodeHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldAppCode, v))
}

// AppCodeEqualFold applies the EqualFold predicate on the "app_code" field.
func AppCodeEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldAppCode, v))
}

// AppCodeContainsFold applies the ContainsFold predicate on the "app_code" field.
func AppCodeContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldAppCode, v))
}

// AppNameEQ applies the EQ predicate on the "app_name" field.
func AppNameEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldAppName, v))
}

// AppNameNEQ applies the NEQ predicate on the "app_name" field.
func AppNameNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldAppName, v))
}

// AppNameIn applies the In predicate on the "app_name" field.
func AppNameIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldAppName, vs...))
}

// AppNameNotIn applies the NotIn predicate on the "app_name" field.
func AppNameNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldAppName, vs...))
}

// AppNameGT applies the GT predicate on the "app_name" field.
func AppNameGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldAppName, v))
}

// AppNameGTE applies the GTE predicate on the "app_name" field.
func AppNameGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldAppName, v))
}

// AppNameLT applies the LT predicate on the "app_name" field.
func AppNameLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldAppName, v))
}

// AppNameLTE applies the LTE predicate on the "app_name" field.
func AppNameLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldAppName, v))
}

// AppNameContains applies the Contains predicate on the "app_name" field.
func AppNameContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldAppName, v))
}

// AppNameHasPrefix applies the HasPrefix predicate on the "app_name" field.
func AppNameHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldAppName, v))
}

// AppNameHasSuffix applies the HasSuffix predicate on the "app_name" field.
func AppNameHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldAppName, v))
}

// AppNameEqualFold applies the EqualFold predicate on the "app_name" field.
func AppNameEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldAppName, v))
}

// AppNameContainsFold applies the ContainsFold predicate on the "app_name" field.
func AppNameContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldAppName, v))
}

// HasAuthorizations applies the HasEdge predicate on the "authorizations" edge.
func HasAuthorizations() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AuthorizationsTable, AuthorizationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorizationsWith applies the HasEdge predicate on the "authorizations" edge with a given conditions (other predicates).
func HasAuthorizationsWith(preds ...predicate.UserAppAuthorization) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newAuthorizationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSessions applies the HasEdge predicate on the "sessions" edge.
func HasSessions() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionsWith applies the HasEdge predicate on the "sessions" edge with a given conditions (other predicates).
func HasSessionsWith(preds ...predicate.Session) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.App) predicate.App {
	return predicate.App(sql.NotPredicates(p))
}
