app_env: "development"

server:
  port: "8081"

grpc_server:
  port: "9091"

id_generator:
  addr: "localhost:50059"

database:
  driver: "postgres"
  source: "" # 机密数据，请在 .env 中设置 DATABASE_SOURCE
  auto_migrate: true

redis:
  addr: "localhost:6379"
  password: "" # 机密数据，请在 .env 中设置 REDIS_PASSWORD
  db: 0

jwt:
  secret: "" # 机密数据，请在 .env 中设置 JWT_SECRET

kafka:
  brokers: "localhost:9092"
  topic_user_registered: "user.registered"

otel:
  jaeger_endpoint: "localhost:4318"
  service_name: "user-platform"

metrics:
  port: "9092" # gRPC 管理端口，暴露 /metrics /healthz /readyz
