basePath: /
definitions:
  model.CreatePasteRequest:
    properties:
      content:
        type: string
      language:
        type: string
      short_link:
        type: string
    required:
    - content
    - language
    - short_link
    type: object
  model.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.LoginResponse:
    properties:
      email:
        type: string
      token:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
  model.PasteResponse:
    properties:
      content:
        type: string
      created_at:
        type: string
      language:
        type: string
      short_link:
        type: string
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.RegisterResponse:
    properties:
      email:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: 用户中心服务，提供注册、登录功能
  title: GopherPaste User Service
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResponse'
      summary: 用户登录
      tags:
      - User
  /pastes:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreatePasteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PasteResponse'
      summary: 创建代码片段
      tags:
      - pastes
  /pastes/{id}:
    get:
      parameters:
      - description: 短链接ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PasteResponse'
      summary: 获取代码片段
      tags:
      - pastes
  /register:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: 注册信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.RegisterResponse'
      summary: 用户注册
      tags:
      - User
swagger: "2.0"
